# Ejercicio 03 - Entrar en un contenedor y navegar por sus carpetas
#
# Este ejercicio consiste en conseguir construir un contenedor y poder entrar para ver su contenido
# Utilizaremos una imagen de node 16. Al entrar podreis ver la version de las herramientas instaladas y demas

# El entrar a los contenedores nos permitira buscar problemas, como por ejemplo, ver si los archivos que buscamos
# estan en la ruta correcta
# ====================================================================================================================================

# Utilizamos la imagen de node16, que tiene mas herramientas instaladas

FROM node:16

# Se usa para cambiar al directorio $HOME para la ejecucion de la aplicacion a /app

WORKDIR /app

# Podemos ver en que directorio estamos situados usando el comando pwd

CMD pwd