DROP DATABASE IF EXISTS login;
CREATE DATABASE login CHARSET utf8mb4;
USE login;

CREATE TABLE usuarios(
	IdUsuario INT UNSIGNED AUTO_INCREMENT,
    Usuario VARCHAR(45) NOT NULL,
    Contrasena VARCHAR(45) NOT NULL,
    FechaRegistro DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(IdUsuario)
);