-- Piedras

insert into tipo_piedra values (1,'Piedra trueno');
insert into tipo_piedra values (2,'Piedra fuego');
insert into tipo_piedra values (3,'Piedra agua');
insert into tipo_piedra values (4,'Piedra lunar');
insert into tipo_piedra values (5,'Piedra hoja');


-- Tipo evolucion

insert into tipo_evolucion values (1,'Nivel');
insert into tipo_evolucion values (2,'Piedra');
insert into tipo_evolucion values (3,'Intercambio');

-- Formas de evolucion

insert into forma_evolucion values (1, 3);
insert into forma_evolucion values (2, 2);
insert into forma_evolucion values (3, 2);
insert into forma_evolucion values (4, 2);
insert into forma_evolucion values (5, 1);
insert into forma_evolucion values (6, 1);
insert into forma_evolucion values (7, 1);
insert into forma_evolucion values (8, 1);
insert into forma_evolucion values (9, 1);
insert into forma_evolucion values (10, 1);
insert into forma_evolucion values (11, 1);
insert into forma_evolucion values (12, 1);
insert into forma_evolucion values (13, 2);
insert into forma_evolucion values (14, 1);
insert into forma_evolucion values (15, 2);
insert into forma_evolucion values (16, 1);
insert into forma_evolucion values (17, 1);
insert into forma_evolucion values (18, 1);
insert into forma_evolucion values (19, 1);
insert into forma_evolucion values (20, 1);
insert into forma_evolucion values (21, 1);
insert into forma_evolucion values (22, 1);
insert into forma_evolucion values (23, 1);
insert into forma_evolucion values (24, 1);
insert into forma_evolucion values (25, 1);
insert into forma_evolucion values (26, 1);
insert into forma_evolucion values (27, 1);
insert into forma_evolucion values (28, 1);
insert into forma_evolucion values (29, 1);

-- Formas de evolucion nivel

insert into nivel_evolucion values (5, 7);
insert into nivel_evolucion values (6, 10);
insert into nivel_evolucion values (7, 16);
insert into nivel_evolucion values (8, 18);
insert into nivel_evolucion values (9, 20);
insert into nivel_evolucion values (10, 22);
insert into nivel_evolucion values (11, 32);
insert into nivel_evolucion values (12, 36);
insert into nivel_evolucion values (14, 21);
insert into nivel_evolucion values (16, 24);
insert into nivel_evolucion values (17, 31);
insert into nivel_evolucion values (18, 26);
insert into nivel_evolucion values (19, 28);
insert into nivel_evolucion values (20, 33);
insert into nivel_evolucion values (21, 25);
insert into nivel_evolucion values (22, 30);
insert into nivel_evolucion values (23, 40);
insert into nivel_evolucion values (24, 37);
insert into nivel_evolucion values (25, 34);
insert into nivel_evolucion values (26, 38);
insert into nivel_evolucion values (27, 35);
insert into nivel_evolucion values (28, 42);
insert into nivel_evolucion values (29, 55);

-- Formas de evolucion piedras

insert into piedra values (2, 1);
insert into piedra values (3, 2);
insert into piedra values (4, 3);
insert into piedra values (13, 4);
insert into piedra values (15, 5);

-- Formas de evolucion pokemon

insert into pokemon_forma_evolucion values (1, 7);
insert into pokemon_forma_evolucion values (2, 11);
insert into pokemon_forma_evolucion values (4, 7);
insert into pokemon_forma_evolucion values (5, 12);
insert into pokemon_forma_evolucion values (7, 7);
insert into pokemon_forma_evolucion values (8, 12);
insert into pokemon_forma_evolucion values (10, 5);
insert into pokemon_forma_evolucion values (11, 6);
insert into pokemon_forma_evolucion values (13, 5);
insert into pokemon_forma_evolucion values (14, 6);
insert into pokemon_forma_evolucion values (16, 8);
insert into pokemon_forma_evolucion values (17, 12);
insert into pokemon_forma_evolucion values (19, 9);
insert into pokemon_forma_evolucion values (21, 9);
insert into pokemon_forma_evolucion values (23, 10);
insert into pokemon_forma_evolucion values (25, 2);
insert into pokemon_forma_evolucion values (27, 10);
insert into pokemon_forma_evolucion values (29, 8);
insert into pokemon_forma_evolucion values (30, 13);
insert into pokemon_forma_evolucion values (32, 8);
insert into pokemon_forma_evolucion values (33, 13);
insert into pokemon_forma_evolucion values (35, 13);
insert into pokemon_forma_evolucion values (37, 3);
insert into pokemon_forma_evolucion values (39, 13);
insert into pokemon_forma_evolucion values (41, 10);
insert into pokemon_forma_evolucion values (43, 14);
insert into pokemon_forma_evolucion values (44, 15);
insert into pokemon_forma_evolucion values (46, 16);
insert into pokemon_forma_evolucion values (48, 17);
insert into pokemon_forma_evolucion values (50, 18);
insert into pokemon_forma_evolucion values (52, 19);
insert into pokemon_forma_evolucion values (54, 20);
insert into pokemon_forma_evolucion values (56, 19);
insert into pokemon_forma_evolucion values (58, 3);
insert into pokemon_forma_evolucion values (60, 21);
insert into pokemon_forma_evolucion values (61, 4);
insert into pokemon_forma_evolucion values (63, 7);
insert into pokemon_forma_evolucion values (64, 1);
insert into pokemon_forma_evolucion values (66, 19);
insert into pokemon_forma_evolucion values (67, 1);
insert into pokemon_forma_evolucion values (69, 14);
insert into pokemon_forma_evolucion values (70, 15);
insert into pokemon_forma_evolucion values (72, 22);
insert into pokemon_forma_evolucion values (74, 21);
insert into pokemon_forma_evolucion values (75, 1);
insert into pokemon_forma_evolucion values (77, 23);
insert into pokemon_forma_evolucion values (79, 24);
insert into pokemon_forma_evolucion values (81, 22);
insert into pokemon_forma_evolucion values (84, 17);
insert into pokemon_forma_evolucion values (86, 25);
insert into pokemon_forma_evolucion values (88, 26);
insert into pokemon_forma_evolucion values (90, 4);
insert into pokemon_forma_evolucion values (92, 21);
insert into pokemon_forma_evolucion values (93, 1);
insert into pokemon_forma_evolucion values (96, 18);
insert into pokemon_forma_evolucion values (98, 19);
insert into pokemon_forma_evolucion values (100, 22);
insert into pokemon_forma_evolucion values (102, 15);
insert into pokemon_forma_evolucion values (104, 19);
insert into pokemon_forma_evolucion values (109, 27);
insert into pokemon_forma_evolucion values (111, 28);
insert into pokemon_forma_evolucion values (116, 11);
insert into pokemon_forma_evolucion values (118, 20);
insert into pokemon_forma_evolucion values (120, 4);
insert into pokemon_forma_evolucion values (129, 9);
insert into pokemon_forma_evolucion values (133, 2);
insert into pokemon_forma_evolucion values (133, 3);
insert into pokemon_forma_evolucion values (133, 4);
insert into pokemon_forma_evolucion values (138, 23);
insert into pokemon_forma_evolucion values (140, 23);
insert into pokemon_forma_evolucion values (147, 22);
insert into pokemon_forma_evolucion values (148, 29);
-- Tipos de aprendizaje

insert into tipo_forma_aprendizaje values(1, 'MT');
insert into tipo_forma_aprendizaje values(2, 'MO');
insert into tipo_forma_aprendizaje values(3, 'Nivel');

-- Forma aprendizaje

insert into forma_aprendizaje values(1, 1);
insert into forma_aprendizaje values(2, 1);
insert into forma_aprendizaje values(3, 1);
insert into forma_aprendizaje values(4, 1);
insert into forma_aprendizaje values(5, 1);
insert into forma_aprendizaje values(6, 1);
insert into forma_aprendizaje values(7, 1);
insert into forma_aprendizaje values(8, 1);
insert into forma_aprendizaje values(9, 1);
insert into forma_aprendizaje values(10, 1);
insert into forma_aprendizaje values(11, 1);
insert into forma_aprendizaje values(12, 1);
insert into forma_aprendizaje values(13, 1);
insert into forma_aprendizaje values(14, 1);
insert into forma_aprendizaje values(15, 1);
insert into forma_aprendizaje values(16, 1);
insert into forma_aprendizaje values(17, 1);
insert into forma_aprendizaje values(18, 1);
insert into forma_aprendizaje values(19, 1);
insert into forma_aprendizaje values(20, 1);
insert into forma_aprendizaje values(21, 1);
insert into forma_aprendizaje values(22, 1);
insert into forma_aprendizaje values(23, 1);
insert into forma_aprendizaje values(24, 1);
insert into forma_aprendizaje values(25, 1);
insert into forma_aprendizaje values(26, 1);
insert into forma_aprendizaje values(27, 1);
insert into forma_aprendizaje values(28, 1);
insert into forma_aprendizaje values(29, 1);
insert into forma_aprendizaje values(30, 1);
insert into forma_aprendizaje values(31, 1);
insert into forma_aprendizaje values(32, 1);
insert into forma_aprendizaje values(33, 1);
insert into forma_aprendizaje values(34, 1);
insert into forma_aprendizaje values(35, 1);
insert into forma_aprendizaje values(36, 1);
insert into forma_aprendizaje values(37, 1);
insert into forma_aprendizaje values(38, 1);
insert into forma_aprendizaje values(39, 1);
insert into forma_aprendizaje values(40, 1);
insert into forma_aprendizaje values(41, 1);
insert into forma_aprendizaje values(42, 1);
insert into forma_aprendizaje values(43, 1);
insert into forma_aprendizaje values(44, 1);
insert into forma_aprendizaje values(45, 1);
insert into forma_aprendizaje values(46, 1);
insert into forma_aprendizaje values(47, 1);
insert into forma_aprendizaje values(48, 1);
insert into forma_aprendizaje values(49, 1);
insert into forma_aprendizaje values(50, 1);
insert into forma_aprendizaje values(51, 2);
insert into forma_aprendizaje values(52, 2);
insert into forma_aprendizaje values(53, 2);
insert into forma_aprendizaje values(54, 2);
insert into forma_aprendizaje values(55, 2);
insert into forma_aprendizaje values(56, 3);
insert into forma_aprendizaje values(57, 3);
insert into forma_aprendizaje values(58, 3);
insert into forma_aprendizaje values(59, 3);
insert into forma_aprendizaje values(60, 3);
insert into forma_aprendizaje values(61, 3);
insert into forma_aprendizaje values(62, 3);
insert into forma_aprendizaje values(63, 3);
insert into forma_aprendizaje values(64, 3);
insert into forma_aprendizaje values(65, 3);
insert into forma_aprendizaje values(66, 3);
insert into forma_aprendizaje values(67, 3);
insert into forma_aprendizaje values(68, 3);
insert into forma_aprendizaje values(69, 3);
insert into forma_aprendizaje values(70, 3);
insert into forma_aprendizaje values(71, 3);
insert into forma_aprendizaje values(72, 3);
insert into forma_aprendizaje values(73, 3);
insert into forma_aprendizaje values(74,3);
insert into forma_aprendizaje values(75,3);
insert into forma_aprendizaje values(76,3);
insert into forma_aprendizaje values(77,3);
insert into forma_aprendizaje values(78,3);
insert into forma_aprendizaje values(79,3);
insert into forma_aprendizaje values(80,3);
insert into forma_aprendizaje values(81,3);
insert into forma_aprendizaje values(82,3);
insert into forma_aprendizaje values(83,3);
insert into forma_aprendizaje values(84,3);
insert into forma_aprendizaje values(85,3);
insert into forma_aprendizaje values(86,3);
insert into forma_aprendizaje values(87,3);
insert into forma_aprendizaje values(88,3);
insert into forma_aprendizaje values(89,3);
insert into forma_aprendizaje values(90,3);
insert into forma_aprendizaje values(91,3);
insert into forma_aprendizaje values(92,3);
insert into forma_aprendizaje values(93,3);
insert into forma_aprendizaje values(94,3);
insert into forma_aprendizaje values(95,3);
insert into forma_aprendizaje values(96,3);
insert into forma_aprendizaje values(97,3);
insert into forma_aprendizaje values(98,3);
insert into forma_aprendizaje values(99,3);
insert into forma_aprendizaje values(100,3);
insert into forma_aprendizaje values(101,3);
insert into forma_aprendizaje values(102,3);
insert into forma_aprendizaje values(103,3);
insert into forma_aprendizaje values(104,3);
insert into forma_aprendizaje values(105,3);
insert into forma_aprendizaje values(106,3);
insert into forma_aprendizaje values(107,3);
insert into forma_aprendizaje values(108,3);
insert into forma_aprendizaje values(109,3);
insert into forma_aprendizaje values(110,3);
insert into forma_aprendizaje values(111,3);
insert into forma_aprendizaje values(112,3);
insert into forma_aprendizaje values(113,3);
insert into forma_aprendizaje values(114,3);
insert into forma_aprendizaje values(115,3);
insert into forma_aprendizaje values(116,3);
insert into forma_aprendizaje values(117,3);

-- Nivel

insert into nivel_aprendizaje values(56, 1);
insert into nivel_aprendizaje values(57, 7);
insert into nivel_aprendizaje values(58, 13);
insert into nivel_aprendizaje values(59, 20);
insert into nivel_aprendizaje values(60, 27);
insert into nivel_aprendizaje values(61, 34);
insert into nivel_aprendizaje values(62, 41);
insert into nivel_aprendizaje values(63, 48);
insert into nivel_aprendizaje values(64, 22);
insert into nivel_aprendizaje values(65, 30);
insert into nivel_aprendizaje values(66, 38);
insert into nivel_aprendizaje values(67, 46);
insert into nivel_aprendizaje values(68, 54);
insert into nivel_aprendizaje values(69, 43);
insert into nivel_aprendizaje values(70, 55);
insert into nivel_aprendizaje values(71, 65);
insert into nivel_aprendizaje values(72, 9);
insert into nivel_aprendizaje values(73, 15);
insert into nivel_aprendizaje values(74,24);
insert into nivel_aprendizaje values(75,33);
insert into nivel_aprendizaje values(76,42);
insert into nivel_aprendizaje values(77,56);
insert into nivel_aprendizaje values(78,36);
insert into nivel_aprendizaje values(79,8);
insert into nivel_aprendizaje values(80,28);
insert into nivel_aprendizaje values(81,35);
insert into nivel_aprendizaje values(82,31);
insert into nivel_aprendizaje values(83,39);
insert into nivel_aprendizaje values(84,47);
insert into nivel_aprendizaje values(85,52);
insert into nivel_aprendizaje values(86,12);
insert into nivel_aprendizaje values(87,16);
insert into nivel_aprendizaje values(88,17);
insert into nivel_aprendizaje values(89,21);
insert into nivel_aprendizaje values(90,26);
insert into nivel_aprendizaje values(91,32);
insert into nivel_aprendizaje values(92,25);
insert into nivel_aprendizaje values(93,5);
insert into nivel_aprendizaje values(94,19);
insert into nivel_aprendizaje values(95,44);
insert into nivel_aprendizaje values(96,40);
insert into nivel_aprendizaje values(97,49);
insert into nivel_aprendizaje values(98,14);
insert into nivel_aprendizaje values(99,23);
insert into nivel_aprendizaje values(100,29);
insert into nivel_aprendizaje values(101,10);
insert into nivel_aprendizaje values(102,50);
insert into nivel_aprendizaje values(103,37);
insert into nivel_aprendizaje values(104,51);
insert into nivel_aprendizaje values(105,59);
insert into nivel_aprendizaje values(106,18);
insert into nivel_aprendizaje values(107,45);
insert into nivel_aprendizaje values(108,11);
insert into nivel_aprendizaje values(109,53);
insert into nivel_aprendizaje values(110,60);
insert into nivel_aprendizaje values(111,64);
insert into nivel_aprendizaje values(112,58);
insert into nivel_aprendizaje values(113,63);
insert into nivel_aprendizaje values(114,66);
insert into nivel_aprendizaje values(115,70);
insert into nivel_aprendizaje values(116,75);
insert into nivel_aprendizaje values(117,81);

-- MT

insert into MT values(1, 'MT01');
insert into MT values(2, 'MT02');
insert into MT values(3, 'MT03');
insert into MT values(4, 'MT04');
insert into MT values(5, 'MT05');
insert into MT values(6, 'MT06');
insert into MT values(7, 'MT07');
insert into MT values(8, 'MT08');
insert into MT values(9, 'MT09');
insert into MT values(10, 'MT10');
insert into MT values(11, 'MT11');
insert into MT values(12, 'MT12');
insert into MT values(13, 'MT13');
insert into MT values(14, 'MT14');
insert into MT values(15, 'MT15');
insert into MT values(16, 'MT16');
insert into MT values(17, 'MT17');
insert into MT values(18, 'MT18');
insert into MT values(19, 'MT19');
insert into MT values(20, 'MT20');
insert into MT values(21, 'MT21');
insert into MT values(22, 'MT22');
insert into MT values(23, 'MT23');
insert into MT values(24, 'MT24');
insert into MT values(25, 'MT25');
insert into MT values(26, 'MT26');
insert into MT values(27, 'MT27');
insert into MT values(28, 'MT28');
insert into MT values(29, 'MT29');
insert into MT values(30, 'MT30');
insert into MT values(31, 'MT31');
insert into MT values(32, 'MT32');
insert into MT values(33, 'MT33');
insert into MT values(34, 'MT34');
insert into MT values(35, 'MT35');
insert into MT values(36, 'MT36');
insert into MT values(37, 'MT37');
insert into MT values(38, 'MT38');
insert into MT values(39, 'MT39');
insert into MT values(40, 'MT40');
insert into MT values(41, 'MT41');
insert into MT values(42, 'MT42');
insert into MT values(43, 'MT43');
insert into MT values(44, 'MT44');
insert into MT values(45, 'MT45');
insert into MT values(46, 'MT46');
insert into MT values(47, 'MT47');
insert into MT values(48, 'MT48');
insert into MT values(49, 'MT49');
insert into MT values(50, 'MT50');

-- MO

insert into MO values(51, 'MO01');
insert into MO values(52, 'MO02');
insert into MO values(53, 'MO03');
insert into MO values(54, 'MO04');
insert into MO values(55, 'MO05');

/* Evoluciona de */
insert into evoluciona_de values(2,1);
insert into evoluciona_de values(3,2);
insert into evoluciona_de values(5,4);
insert into evoluciona_de values(5,6);
insert into evoluciona_de values(6,5);
insert into evoluciona_de values(8,7);
insert into evoluciona_de values(9,8);
insert into evoluciona_de values(11,10);
insert into evoluciona_de values(12,11);
insert into evoluciona_de values(14,13);
insert into evoluciona_de values(15,14);
insert into evoluciona_de values(17,16);
insert into evoluciona_de values(18,17);
insert into evoluciona_de values(20,19);
insert into evoluciona_de values(22,21);
insert into evoluciona_de values(24,23);
insert into evoluciona_de values(26,25);
insert into evoluciona_de values(28,27);
insert into evoluciona_de values(30,29);
insert into evoluciona_de values(31,30);
insert into evoluciona_de values(33,32);
insert into evoluciona_de values(34,33);
insert into evoluciona_de values(36,35);
insert into evoluciona_de values(38,37);
insert into evoluciona_de values(40,39);
insert into evoluciona_de values(42,41);
insert into evoluciona_de values(44,43);
insert into evoluciona_de values(45,44);
insert into evoluciona_de values(47,46);
insert into evoluciona_de values(49,48);
insert into evoluciona_de values(51,50);
insert into evoluciona_de values(53,52);
insert into evoluciona_de values(55,54);
insert into evoluciona_de values(57,56);
insert into evoluciona_de values(59,58);
insert into evoluciona_de values(61,60);
insert into evoluciona_de values(62,61);
insert into evoluciona_de values(64,63);
insert into evoluciona_de values(65,64);
insert into evoluciona_de values(67,66);
insert into evoluciona_de values(68,67);
insert into evoluciona_de values(70,69);
insert into evoluciona_de values(71,70);		
insert into evoluciona_de values(73,72);
insert into evoluciona_de values(75,74);
insert into evoluciona_de values(76,75);
insert into evoluciona_de values(78,77);
insert into evoluciona_de values(80,79);
insert into evoluciona_de values(82,81);
insert into evoluciona_de values(85,84);
insert into evoluciona_de values(87,86);
insert into evoluciona_de values(89,88);
insert into evoluciona_de values(91,90);
insert into evoluciona_de values(93,92);
insert into evoluciona_de values(94,93);
insert into evoluciona_de values(97,96);
insert into evoluciona_de values(99,98);
insert into evoluciona_de values(101,100);
insert into evoluciona_de values(103,102);
insert into evoluciona_de values(105,104);
insert into evoluciona_de values(110,109);
insert into evoluciona_de values(112,111);
insert into evoluciona_de values(117,116);
insert into evoluciona_de values(119,118);
insert into evoluciona_de values(121,120);
insert into evoluciona_de values(130,129);
insert into evoluciona_de values(134,133);
insert into evoluciona_de values(135,133);
insert into evoluciona_de values(136,133);
insert into evoluciona_de values(139,138);
insert into evoluciona_de values(141,140);
insert into evoluciona_de values(148,147);
insert into evoluciona_de values(149,148);
